### ISSUE TITLE
Support base images stored in internal registry

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/ci-service-integration-library#4]
If we want to use this to build an image based on this Dockerfile:
```
FROM registry.speag.com/osparc/base/ubuntu-focal/matlab-runtime:R2020b as base
```
The pipeline cannot pull the base image (access denied to that registry).

**Comment by GitHK** [comment]
To achieve something like this, we need to extend the `RepoModel` to add additional keywords supporting `before_STAGE_commands` like: `before_build_commands`, `before_test_commands` and ``before_publish_commands`. These will allow to run a docker losing and then run the usual commands like docker build.

**Comment by elisabettai** [comment]
This was fixed I think, we're able to use images that are on the internal registry.
